# generates tables.h for the toy scanner DFA
# States 0-14, merged from Ident/IntLit/operators/comparison-cluster/whitespace

DEAD = -1

CHAR_CLASSES = ['letter', 'digit19', 'zero', 'plus', 'minus',
                'star', 'slash', 'lt', 'gt', 'eq', 'ws']

def dead_row():
    return {c: DEAD for c in CHAR_CLASSES}

transitions = {
    0: {'letter': 1, 'digit19': 2, 'zero': 3, 'plus': 4, 'minus': 5,
        'star': 6, 'slash': 7, 'lt': 8, 'gt': 10, 'eq': 12, 'ws': 14},

    1: {**dead_row(), 'letter': 1, 'digit19': 1, 'zero': 1},  # Ident
    2: {**dead_row(), 'digit19': 2, 'zero': 2},                # IntLit [1-9][0-9]*
    3: dead_row(),                                             # IntLit "0"

    4: dead_row(),  # Plus
    5: dead_row(),  # Minus
    6: dead_row(),  # Star
    7: dead_row(),  # Slash

    8:  {**dead_row(), 'eq': 9},    # Lt -> Le
    9:  dead_row(),                 # Le
    10: {**dead_row(), 'eq': 11},   # Gt -> Ge
    11: dead_row(),                 # Ge
    12: {**dead_row(), 'eq': 13},   # Assign -> Eq
    13: dead_row(),                 # Eq

    14: {**dead_row(), 'ws': 14},   # whitespace/comment
}

# None = not accepting
accept_type = {
    0: None, 1: 'Ident', 2: 'IntLit', 3: 'IntLit',
    4: 'Plus', 5: 'Minus', 6: 'Star', 7: 'Slash',
    8: 'Lt', 9: 'Le', 10: 'Gt', 11: 'Ge',
    12: 'Assign', 13: 'Eq', 14: None
}

NUM_STATES = len(transitions)
NUM_CLASSES = len(CHAR_CLASSES)

with open("tables.hpp", "w") as f:
    def w(line=""):
        f.write(line + "\n")

    w("// AUTO-GENERATED by gen_tables.py, do not hand-edit")
    w("#pragma once")
    w('#include "token.hpp"')
    w()
    w(f"constexpr int NUM_STATES = {NUM_STATES};")
    w(f"constexpr int NUM_CLASSES = {NUM_CLASSES};")
    w(f"constexpr int DEAD = {DEAD};")
    w()

    w("// Char class order: " + ", ".join(CHAR_CLASSES))
    w("inline int delta[NUM_STATES][NUM_CLASSES] = {")
    for state in sorted(transitions):
        row = transitions[state]
        vals = ", ".join(str(row[c]) for c in CHAR_CLASSES)
        w(f"  {{ {vals} }}, // state {state}")
    w("};")
    w()

    w("inline bool accept[NUM_STATES] = {")
    vals = ", ".join("true" if accept_type[s] is not None else "false" for s in sorted(accept_type))
    w(f"  {vals}")
    w("};")
    w()

    w("inline TokenType tokenType[NUM_STATES] = {")
    vals = ", ".join(
        f"TokenType::{accept_type[s]}" if accept_type[s] else "TokenType::None"
        for s in sorted(accept_type)
    )
    w(f"  {vals}")
    w("};")

print("tables.h generated.")